#pragma once
#define _DISABLE_VECTOR_ANNOTATION
#define _DISABLE_STRING_ANNOTATION
#define GLFW_INCLUDE_VULKAN
#define GLM_FORCE_RADIANS

#define WIDTH 280
#define HEIGHT 1010
#define POS_X 1640
#define POS_Y 30
#define VERTICAL
//#define HIDE_CONSOLE

typedef float INPUT_TYPE;
#define INPUT_FORMAT RTAUDIO_FLOAT32
#define INPUT_SCALE  1.0

typedef float OUTPUT_TYPE;
#define OUTPUT_FORMAT RTAUDIO_FLOAT32
#define OUTPUT_SCALE  1.0

#define INPUT_BUFFER_TIME 0.1
#define INPUT_BUFFER_SIZE 128
#define OUTPUT_BUFFER_SIZE 128

#define FFT_FRAME_SAMPLES 2048
#define FFT_FRAME_SPACING 512
#define FFT_FRAMES 10
#define IDENTIFY_LATENCY 3
#define VEC4_COUNT (FFT_REAL_SAMPLES / 4)
#define FFT_REAL_SAMPLES (FFT_FRAME_SAMPLES / 2)

#define PREPROCESS_BATCH_SIZE 1500
#define CLIP_LENGTH 15
