#pragma once
#define GLFW_INCLUDE_VULKAN
#define GLM_FORCE_RADIANS

#define WIDTH 280
#define HEIGHT 1010
#define POS_X 1640
#define POS_Y 30
#define VERTICAL
//#define HIDE_CONSOLE

typedef float INPUT_TYPE;
#define INPUT_FORMAT RTAUDIO_FLOAT32
#define INPUT_SCALE  1.0

typedef float OUTPUT_TYPE;
#define OUTPUT_FORMAT RTAUDIO_FLOAT32
#define OUTPUT_SCALE  1.0

#define INPUT_BUFFER_TIME 0.2
#define INPUT_BUFFER_SIZE 128
#define OUTPUT_BUFFER_SIZE 128

#define FFT_FRAME_SAMPLES 1024
#define FFT_FRAME_SPACING (FFT_FRAME_SAMPLES - (FFT_FRAME_SAMPLES / 4))
#define CONTEXT_SIZE 7
#define FFT_FRAMES (CONTEXT_SIZE * 2 + 1)
#define FFT_REAL_SAMPLES (FFT_FRAME_SAMPLES / 2)
#define MEL_BINS 32
#define FRAME_SIZE 24
#define VEC4_COUNT (FRAME_SIZE / 4)
#define MMAX_EXAMPLE_F 5

#define PREPROCESS_BATCH_SIZE 1500
#define CLIP_LENGTH 15

#define STEP_SIZE 0.0001
